# Generated by Django 3.1.6 on 2021-05-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210509_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acc_no', models.IntegerField()),
                ('ifcs_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
