# Generated by Django 3.2.2 on 2021-05-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_bank_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='normal_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whole_seller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistadd', to=settings.AUTH_USER_MODEL)),
                ('wholeseller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistwholeseller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
