# Generated by Django 3.2.2 on 2021-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('question', models.TextField()),
                ('query_image', models.ImageField(blank=True, null=True, upload_to='queryimage/')),
            ],
        ),
    ]
