# Generated by Django 3.2.2 on 2021-06-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_scientist_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farming_Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('youtube_link', models.CharField(max_length=500)),
                ('farming_description', models.TextField()),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='farm_image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Farming_Technique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
